EPOCH: 100
TRAIN:
  EPISODE_PER_EPOCH: 1
  TRAJECTORY_PER_EPISODE : 1000
  TRAJECTORY_BATCH_SIZE : 128
  TRAIN_ITER: 10
  LEARNING_RATE: 0.001
  LATEST_MODEL_NAME: 'latest_model.pt'

RAY:
  NUM_ACTOR: 4
  NUM_TRAINER: 4
  
  CHECKPOINT_MODEL_NAME: 'model.ckpt'

VALIDATE:
  EPISODE_PER_EPOCH: 1
  TRAJECTORY_PER_EPISODE : 1000
  SCORE: 450


WANDB:
  ENABLE: False
  PROJECT_NAME: 'reinforcement_learning'
