NUM_GENERATION: 100
TRAIN:
  NUM_EPISODE: 100
  NUM_TRAJECTORY : 1000
  NUM_EPOCH: 10
  BATCH_SIZE : 64
  LEARNING_RATE: 0.001
  PATIENCE : 10
  LATEST_MODEL_NAME: "latest_model.pt"

RAY:
  NUM_ACTOR: 4
  NUM_TRAINER: 4
  
  CHECKPOINT_MODEL_NAME: "model.ckpt"

VALIDATE:
  NUM_EPISODE: 20
  NUM_TRAJECTORY : 1000
  SCORE: 450


WANDB:
  ENABLE: False
  PROJECT_NAME: "reinforcement_learning"