NAME : "PPO"
MODEL:
  NUM_STATE: 4
  NUM_ACTION: 2

  GAMMA: 0.99
  LAMBDA: 0.95
  EPS_CLIP: 0.2
ENV:
  test: 2

ENV_MODULE : "user_define.environment"
ENV_CLASS : "EnvWrapper"

MODEL_MODULE : "user_define.model"
MODEL_CLASS : "ModelWrapper"